version: "3.3"
services:
  web:
    build: .
    ports:
        - "5000:5000"
    links:
        - mongo
    depends_on:
        - mongo
    environment:
        WAIT_HOSTS: mongo:27017
  mongo:
    container_name: mongo
    image: mongo
    ports:
        - "27017:27017"